services:
  - type: web
    name: sanket-portfolio
    env: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://sanketdhital.com.np
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
